### PR TITLE
Navigation setup

### PR DESCRIPTION
**Pull request by Hiten24**
Navigation setup

### CODE REVIEW

**Review by Horizon733 — CHANGES_REQUESTED** [review]
@Hiten24 @Biren-Nayak Need backstack pop for login and sign up both. Currently I only see Login has back stack pop and not sign up. Please add for Sign up and then **i will merge**

**Comment by Biren-Nayak** [comment]
> @Hiten24 @Biren-Nayak Need backstack pop for login and sign up both. Currently I only see Login has back stack pop and not sign up. Please add for Sign up and then **i will merge**

@Horizon733 I actually am using popUpto() instead of popBackStack(), which should remove every entry until specified value. So, It should work properly, but if it doesn't and causes any unexpected behaviour, please let me know.

**Comment by Horizon733** [comment]
> > @Hiten24 @Biren-Nayak Need backstack pop for login and sign up both. Currently I only see Login has back stack pop and not sign up. Please add for Sign up and then **i will merge**
> 
> @Horizon733 I actually am using popUpto() instead of popBackStack(), which should remove every entry until specified value. So, It should work properly, but if it doesn't and causes any unexpected behaviours, please let me know.

Yes it is not working in sign up page. Add it there too

**Comment by Biren-Nayak** [comment]
> > > @Hiten24 @Biren-Nayak Need backstack pop for login and sign up both. Currently I only see Login has back stack pop and not sign up. Please add for Sign up and then **i will merge**
> > 
> > 
> > @Horizon733 I actually am using popUpto() instead of popBackStack(), which should remove every entry until specified value. So, It should work properly, but if it doesn't and causes any unexpected behaviour, please let me know.
> 
> Yes it is not working in sign up page. Add it there too

@Horizon733 Understood. Added backStack clearance in SignupScreen.kt and did some minor optimization as well.

**Pull request merged**
